language: python
python:
  - 3.6
  - 3.5
  - 2.7
  - pypy
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: required
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - flake8 .
  - coverage run --source=serpy setup.py test
after_success:
  coveralls
