dist: xenial
language: python
python:
  - 3.7
  - 3.6
  - 3.5
  - 2.7
  - pypy2.7-6.0
  - pypy3.5-6.0
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - flake8 .
  - coverage run --source=serpy setup.py test
after_success:
  coveralls
